import { expect, test } from "bun:test";
import { Gen4Parser } from "../../src/parsers/gen4/parser";
const parser = new Gen4Parser("./saves/diamond.sav");

test("It correctly gets empty box slot", () =>{
    expect(parser.getEmptyBoxSlot()).toEqual([10, 29])
})

test("It correctly gets first party pokemon", () =>{
    const party = parser.readParty();
    expect(party[0]).toEqual({
        generation: 4,
        speciesId: 264,
        nickname: "LINOONE",
        experience: 759362,
        heldItemId: 0,
        friendship: 255,
        pokerus: 80,
        ot: {
            name: "BOT",
            trainerId: 27171,
            secretId: 33452,
            gender: "male",
        },
        personalityValue: 3129958778,
        natureId: 3,
        gender: "female",
        isShiny: false,
        abilitySlot: 0,
        abilityId: 53,
        ivs: { hp: 12, attack: 12, defense: 3, speed: 25, specialAttack: 13, specialDefense: 15 },
        evs: { hp: 112, attack: 148, defense: 63, speed: 55, specialAttack: 71, specialDefense: 61 },
        contest: {
            coolness: 0,
            beauty: 0,
            cuteness: 0,
            smartness: 0,
            toughness: 0,
            feel: 0,
        },
        moves: [
            { moveId: 57, pp: 15, ppUps: 0 },
            { moveId: 154, pp: 15, ppUps: 0 },
            { moveId: 343, pp: 40, ppUps: 0 },
            { moveId: 29, pp: 15, ppUps: 0 },
        ],
        met: { locationId: 55, levelMet: 81, originGameId: 3, ballId: 4 },
        hiddenPower: { typeId: 14, power: 52 },
        ribbons: 1,
        markings: {
            circle: false,
            triangle: false,
            square: false,
            heart: false,
            star: false,
            diamond: false,
        },
        isEgg: false,
        isNicknamed: false,
        languageId: 2,
        formId: 0,
        status: {
            sleepTurns: 0,
            poison: false,
            burn: false,
            freeze: false,
            paralysis: false,
            badlyPoisoned: false,
        },
        level: 91,
        currentHp: 279,
        stats: {
            hp: 279,
            attack: 193,
            defense: 132,
            speed: 221,
            specialAttack: 110,
            specialDefense: 143,
        },
    })
})

test("It correctly gets last party pokemon", () =>{
    const party = parser.readParty();
    expect(party.at(-1)).toEqual({
        generation: 4,
        speciesId: 264,
        nickname: "LINOONE",
        experience: 792098,
        heldItemId: 0,
        friendship: 255,
        pokerus: 80,
        ot: {
            name: "BOT",
            trainerId: 27171,
            secretId: 33452,
            gender: "male",
        },
        personalityValue: 1783370837,
        natureId: 12,
        gender: "female",
        isShiny: false,
        abilitySlot: 1,
        abilityId: 53,
        ivs: { hp: 30, attack: 4, defense: 24, speed: 28, specialAttack: 28, specialDefense: 24 },
        evs: { hp: 141, attack: 108, defense: 3, speed: 186, specialAttack: 12, specialDefense: 60 },
        contest: {
            coolness: 0,
            beauty: 0,
            cuteness: 0,
            smartness: 0,
            toughness: 0,
            feel: 0,
        },
        moves: [
            { moveId: 70, pp: 15, ppUps: 0 },
            { moveId: 154, pp: 15, ppUps: 0 },
            { moveId: 343, pp: 40, ppUps: 0 },
            { moveId: 163, pp: 20, ppUps: 0 },
        ],
        met: { locationId: 55, levelMet: 81, originGameId: 3, ballId: 4 },
        hiddenPower: { typeId: 0, power: 30 },
        ribbons: 1,
        markings: {
            circle: false,
            triangle: false,
            square: false,
            heart: false,
            star: false,
            diamond: false,
        },
        isEgg: false,
        isNicknamed: false,
        languageId: 2,
        formId: 0,
        status: {
            sleepTurns: 0,
            poison: false,
            burn: false,
            freeze: false,
            paralysis: false,
            badlyPoisoned: false,
        },
        level: 92,
        currentHp: 305,
        stats: {
            hp: 305,
            attack: 162,
            defense: 139,
            speed: 257,
            specialAttack: 125,
            specialDefense: 153,
        },
    })
})

test("It correctly gets the first pokemon at the first box", () =>{
    const box = parser.readBox(0);
    expect(box[0]).toEqual({
        generation: 4,
        speciesId: 402,
        nickname: "KRICKETUNE",
        experience: 575,
        heldItemId: 0,
        friendship: 117,
        pokerus: 0,
        ot: {
            name: "Jack",
            trainerId: 32409,
            secretId: 16630,
            gender: "male",
        },
        personalityValue: 3536645379,
        natureId: 4,
        gender: "female",
        isShiny: false,
        abilitySlot: 1,
        abilityId: 68,
        ivs: { hp: 13, attack: 5, defense: 17, speed: 25, specialAttack: 31, specialDefense: 22 },
        evs: { hp: 7, attack: 10, defense: 1, speed: 12, specialAttack: 1, specialDefense: 0 },
        contest: {
            coolness: 0,
            beauty: 0,
            cuteness: 0,
            smartness: 0,
            toughness: 0,
            feel: 0,
        },
        moves: [
            { moveId: 45, pp: 40, ppUps: 0 },
            { moveId: 117, pp: 10, ppUps: 0 },
            { moveId: 210, pp: 20, ppUps: 0 },
        ],
        met: { locationId: 17, levelMet: 3, originGameId: 10, ballId: 4 },
        hiddenPower: { typeId: 7, power: 60 },
        ribbons: 0,
        markings: {
            circle: false,
            triangle: false,
            square: false,
            heart: false,
            star: false,
            diamond: false,
        },
        isEgg: false,
        isNicknamed: false,
        languageId: 4,
        formId: 0,
    })
})

test("It correctly gets the last pokemon in a box", () =>{
    const box = parser.readBox(0);
    expect(box.at(-1)).toEqual({
        generation: 4,
        speciesId: 405,
        nickname: "LUXRAY",
        experience: 38107,
        heldItemId: 0,
        friendship: 255,
        pokerus: 0,
        ot: {
            name: "Jack",
            trainerId: 32409,
            secretId: 16630,
            gender: "male",
        },
        personalityValue: 1875268745,
        natureId: 20,
        gender: "male",
        isShiny: false,
        abilitySlot: 1,
        abilityId: 22,
        ivs: { hp: 28, attack: 16, defense: 20, speed: 26, specialAttack: 24, specialDefense: 22 },
        evs: { hp: 29, attack: 56, defense: 12, speed: 77, specialAttack: 28, specialDefense: 6 },
        contest: {
            coolness: 0,
            beauty: 0,
            cuteness: 0,
            smartness: 0,
            toughness: 0,
            feel: 0,
        },
        moves: [
            { moveId: 209, pp: 20, ppUps: 0 },
            { moveId: 43, pp: 30, ppUps: 0 },
            { moveId: 268, pp: 20, ppUps: 0 },
            { moveId: 242, pp: 15, ppUps: 0 },
        ],
        met: { locationId: 17, levelMet: 3, originGameId: 10, ballId: 4 },
        hiddenPower: { typeId: 0, power: 55 },
        ribbons: 0,
        markings: {
            circle: false,
            triangle: false,
            square: false,
            heart: false,
            star: false,
            diamond: false,
        },
        isEgg: false,
        isNicknamed: false,
        languageId: 4,
        formId: 0,
    })
})

test("It correctly gets the last pokemon in the last box", () =>{
    const box = parser.readBox(17);
    expect(box.at(-1)).toEqual({
        generation: 4,
        speciesId: 262,
        nickname: "MIGHTYENA",
        experience: 13824,
        heldItemId: 0,
        friendship: 70,
        pokerus: 0,
        ot: {
            name: "Jack",
            trainerId: 32409,
            secretId: 16630,
            gender: "male",
        },
        personalityValue: 274082453,
        natureId: 3,
        gender: "male",
        isShiny: false,
        abilitySlot: 1,
        abilityId: 95,
        ivs: { hp: 26, attack: 28, defense: 23, speed: 26, specialAttack: 14, specialDefense: 31 },
        evs: { hp: 0, attack: 0, defense: 0, speed: 0, specialAttack: 0, specialDefense: 0 },
        contest: {
            coolness: 0,
            beauty: 0,
            cuteness: 0,
            smartness: 0,
            toughness: 0,
            feel: 0,
        },
        moves: [
            { moveId: 28, pp: 15, ppUps: 0 },
            { moveId: 44, pp: 25, ppUps: 0 },
            { moveId: 316, pp: 40, ppUps: 0 },
            { moveId: 46, pp: 20, ppUps: 0 },
        ],
        met: { locationId: 29, levelMet: 24, originGameId: 10, ballId: 15 },
        hiddenPower: { typeId: 8, power: 68 },
        ribbons: 0,
        markings: {
            circle: false,
            triangle: false,
            square: false,
            heart: false,
            star: false,
            diamond: false,
        },
        isEgg: false,
        isNicknamed: false,
        languageId: 4,
        formId: 0,
    })
})
